PUT http://localhost:8080/api/v1/transactions/252
Content-Type: application/json

{
  "description": "Movie ticket",
  "amount": -10.0,
  "convertedAmount": -10.0,
  "currency": "eur",
  "ownerId": 252
}